name: cdr-tracer-roms
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - xarray
  - dask
  - numpy
  - pandas
  - matplotlib
  - netcdf4
  - pyco2sys
  - gcm_filters
  - ipykernel
  - pip
  - pip:
    - roms-tools
